# Generated by Django 4.2.13 on 2024-07-08 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('output', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
